### ISSUE TITLE
some confusion about 4_nmt_model_tutorial

### ISSUE THREAD

**Issue by hanyaqian** [lvapeab/nmt-keras#17]
Hi @lvapeab 

> ctx_mean = MaskedMean()(annotations)
annotations = MaskLayer()(annotations)  # We may want the padded annotations

I did not find an explanation about `MaskedMean` and `MaskLayer ` in the keras document, can you give me a brief explanation? And what do you mean of `the padded annotations`?

Thanks!

**Comment by lvapeab** [comment]
Hello,

the decoder initializes their hidden states by means of a MLP, which takes a mean of the representation of the input sentence (see e.g. the expression before Eq. 7 from this paper: https://arxiv.org/pdf/1502.03044.pdf). Note that, since we work in minibatches, each sentence from a minibatch can have a different length. Therefore, we use masks, in order to know which are the actual words. `MaskedMean()` computes the mean of the annotations, but considering their associated mask.

Similarly, we pass the full sequence of annotations to the decoder, for computing attention on them. But we don't want to give attention to masked annotations. Therefore, we apply the mask on them with `MaskLayer`.

**Comment by hanyaqian** [comment]
Your explanation is very clear, thank you very much again. @lvapeab
